title: "eerio: field report"
author:
  name: Pawe≈Ç Balawender
  email: ruplet at ruplet.com
description: A collection of things I found on the internet :)

remote_theme: jekyll/minima
minima:
  skin: dark
